name: Playwright Tests

run-name: CI running Playwright Tests 🚀

on: push


jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.15.0

      - name: Install Dependencies
        run: npm install --include=dev

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          USER1: ${{ secrets.USER1 }}
          USER2: ${{ secrets.USER2 }}
          USER3: ${{ secrets.USER3 }}
          USER4: ${{ secrets.USER4 }}
          USER5: ${{ secrets.USER5 }}